# Generated by Django 5.2.7 on 2025-10-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgc', models.FloatField()),
                ('musculo', models.FloatField()),
                ('umidade', models.FloatField()),
                ('massa_ossea', models.FloatField()),
                ('tmb', models.FloatField()),
                ('taxa_proteica', models.FloatField()),
                ('idade_corporal', models.IntegerField()),
                ('gordura_viceral', models.IntegerField()),
                ('gordura_subcutanea', models.FloatField()),
                ('peso_ideal', models.FloatField()),
                ('gordura_corporal', models.FloatField()),
                ('peso_sem_gordura', models.FloatField()),
                ('peso_muscular', models.FloatField()),
                ('quantidade_proteina', models.FloatField()),
            ],
        ),
    ]
